### ISSUE TITLE
secondary distributions die if profile can't be found

### ISSUE THREAD

**Issue by Bloodmallet** [Bloodmallet/bloodytools#19]
```python
Traceback (most recent call last):
  File "bloodytools.py", line 1346, in <module>
    main()
  File "bloodytools.py", line 1215, in main
    secondary_distribution_simulation(settings)
  File "/home/bloodmallet/bloodmallet/bloodytools/bloodytools/simulation_objects/secondary_distribution_simulation.py", line 32, in secondary_distribution_simulation
    "secondary_distributions", wow_class, wow_spec, fight_style, settings
  File "/home/bloodmallet/bloodmallet/bloodytools/bloodytools/utils/utils.py", line 195, in create_base_json_dict
    profile = extract_profile(profile_location, wow_class)
  File "/home/bloodmallet/bloodmallet/bloodytools/bloodytools/utils/utils.py", line 134, in extract_profile
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../../SimulationCraft/profiles/Tier25/T25_Priest_Discipline.simc'
```

**Comment by Bloodmallet** [comment]
All simulations should fail horribly during single run mode instead of failing silently.
